### ISSUE TITLE
module circulation

### ISSUE THREAD

**Issue by RogerMoore** [ComputationalPhysiology/circulation#11]
Hi Henrik I installed the module, run returns  'AttributeError: module 'circulation' has no attribute 'print_info'
Did I miss somethink?
Best regards
Mario Medugno

**Comment by finsberg** [comment]
Hi @RogerMoore 

Can you explain which code that produced this error? Did you run any of the examples?

**Comment by finsberg** [comment]
I belive you are referring to the example in the README file, which I now have fixed in #12. Thanks for reporting
